#!/bin/sh
vim .zsh_history << EOF
:g/;gst\s/d
:g/;gco\s/d
:g/;gcam\s/d
:g/;git\sclone/d
:g/;git\sadd/d
:g/;git\spush\s\*$/d
:g/;git\spull\s\*$/d
:g/;git\spush\sorigin\s\w/d
:g/;git\spull\sorigin\s\w/d
:g/;git\sdiff/d
:g/;git\sreset/d
:g/;git\sfetch/d
:g/;git\sbranch/d
:g/;gb\s/d
:g/;\.\+$/d
:g/;\.\+\/\S\+$/d
:g/;ls/d
:g/;ll/d
:g/;rm\s/d
:g/;cd\s/d
:g/;cp\s/d
:g/;mv\s/d
:g/;wc\s/d
:g/;mkdir\s/d
:g/;file\s/d
:g/;find\s\/\s\-name\s\S\+$/d
:g/;vim\s/d
:g/;cat\s\S\+$/d
:g/;echo\s\$/d
:g/;wget\s/d
:g/;ping\s/d
:g/;kill\s/d
:g/;man\s/d
:g/;which\s/d
:g/;whereis\s/d
:g/;touch\s/d
:g/;source\s/d
:g/;export\s/d
:g/;ssh\s/d
:g/;ssh-copy-id\s/d
:g/;j\s/d
:g/;hsi\s/d
:g/;st\s/d
:g/;alias\s/d
:g/;zshconfig\s/d
:g/;rgc\s/d
:g/;removefile\s/d
:g/;open/d
:g/;say/d
:g/;http/d
:g/;python\d\?\s\S\+$/d
:g/;pip\d\?\sinstall/d
:g/;pip\d\?\slist/d
:g/;nginx\s/d
:g/;brew\s/d
:g/;docker\s/d
:g/;bs\s/d
:g/;n\s/d
:g/;cnpm\sinstall/d
:g/;npm\sinstall/d
:g/;npm\srun/d
:g/;node\sinstall.js/d
:g/;mvncist/d
:g/;mvn\sspring-boot:run/d
:g/;mvn\s\w*$/d
:g/;\/Users\/Charles/d
:g/zsh_history/d
:g/;\.\+/d
:g/\s--help\s*$/d
:g/\s-h\s*$/d
:g/\s--version\s*$/d
:g/\s-v\s*$/d
:g/;\w*$/d
:wq
EOF
